### ISSUE TITLE
Limitation of structure enumaration?

### ISSUE THREAD

**Issue by FPrith** [giprayogo/SHRY#15]
I have a fundamental question.
Is it possible to treat "all" solid solutions without exception?

For example, I tried to create two O vacancies in a 2*2*2 SrTiO3 supercell with a simple-perovskite-type structure.
This supercell contains eight Sr atoms, eight Ti atoms, and twenty-four O atoms. 
To do that, O and X (vacancy) occupancies were set to be 0.917 and 0.083 in a CIF file, respectively,.
However, structure enumeration failed due to the possible creation of the non-integer numbers of O atoms and O vacancies, as follows;
Full Formula (X1.992 Sr8 Ti8 O22.008)
Reduced Formula: X1.992Sr8Ti8O22.008

I would be grateful if you could provide me with a plan to overcome this without using larger supercells.

**Comment by kousuke-nakano** [comment]
Dear @FPrith Yes. Would you try to increase the significant digits? e.g., 0.9166666666666666 and 0.08333333333333333. The latest version advises this in its output, but we have not deployed it yet.

**Comment by FPrith** [comment]
Thank you very much for your quick reply.
Your indication can be going well.
The inputs of significant digits are effective to treat the supercell; the command stated below succeeded.
substitutor = Substitutor(structure)

However, the creation of symmetry-nonequivalent structures have not been done.
An error stated below appeared.
AttributeError: 'CifWriter' object has no attribute 'ciffile'

I will modify my scripts based on your SHRY indications.

**Comment by kousuke-nakano** [comment]
Dear @FPrith 

> However, the creation of symmetry-nonequivalent structures have not been done.
An error stated below appeared.
AttributeError: 'CifWriter' object has no attribute 'ciffile'

> I will modify my scripts based on your SHRY indications.

OK. It seems that you are trying to call SHRY from your python script, not on the terminal.

You are suffering from another problem, aren’t you?Would you paste your script? I will have a look at it.

**Comment by FPrith** [comment]
Yes, I'm using SHRY on my Python script.

A Python script for structure enumeration without the Ewald method was pasted here.
Can you see this file?
[srtio3_relaxed.zip](https://github.com/giprayogo/SHRY/files/13717894/srtio3_relaxed.zip)

**Comment by kousuke-nakano** [comment]
Dear @FPrith, I could not reproduce your error. Your script works. I guess the reason is that your `pymatgen` version is a bit old. I have confirmed that `shry` works with `pymatgen` >= 2022.11.7. Would you let me know?

**Comment by FPrith** [comment]
My pymatgen version is pymatgen 2023.12.18.

I found that, when a python library is upgraded to its newer version, errors/cautions appear as stated below:
DEPRECATION: shry 1.1.7 has a non-standard dependency specifier numpy>="1.17".
pip 24.0 will enforce this behaviour change.
A possible replacement is to upgrade to a newer version of shry or contact the author to suggest that they release a version with a conforming dependency specifiers.
Discussion can be found at https://github.com/pypa/pip/issues/12063

Stated above is on numpy, but in fact, other libraries (pymatgen, scipy,,,) are also related to the DEPRECATION cautions.
I'm now reading the content in https://github.com/pypa/pip/issues/12063.
I would appreciate it if you kindly inform me about this issue.

**Comment by kousuke-nakano** [comment]
Dear @FPrith, your pymatgen version 2023.12.18 seems ok. For future versions of shry, I will follow the PEP 440 rule, but I do not think it is related to the bug you are now suffering from.

**Comment by FPrith** [comment]
By using other Jupyter environment, symmetry-inequivalent structures were successfully created.
Thank you very much for your some indications!
The number of symmetry-inequivalent structures in this supercell was seven, wasn't it?

**Comment by kousuke-nakano** [comment]
Dear @FPrith, I have noticed that there is a backward incompatibility in `pymatgen` `v2023.10.11` -> `v2023.12.18`. This is the reason. Would you try to use < v2023.10.11 ? I will add this in `setup.cfg` in the next release of SHRY.

Yes. I think it is seven.

**Comment by kousuke-nakano** [comment]
Dear @FPrith Please feel free to post another discussion if there is unclear stuff, and we would appreciate it if you would cite our [paper](https://doi.org/10.1021/acs.jcim.2c00389) to advertise SHRY when publishing a paper.

**Comment by FPrith** [comment]
I confirmed that symmetry-inequivalent structures were created with pymatgen 2023.10.4.
Thank you very much for your kind advice!
